### ISSUE TITLE
Install on root

### ISSUE THREAD

**Issue by hakimihamdan88** [saleem-hadad/larecipe#116]
Can we install on root without /docs? I like to install on my subdomain eg: http://doc.mysite.com/1.0/

**Comment by saleem-hadad** [comment]
Hi @hakimihamdan88 
yes you can just change the config file => 

```php
    'docs'        => [
        'route'   => '', // leave this empty
        ...
    ],
```

**Comment by ralphmorris** [comment]
Hi @saleem-hadad,

I've installed this on a fresh Laravel site and followed your instructions above but the Default 'Overview' menu item seems to now be linking to http://1.0.0.0/overview instead of my docs.domain.com. If I put the path back in the route parameter the link works again but I need it on the root.

I'm using homestead and have my local dev set up to point to a local subdomain.

Any idea why this is happening? Thanks
