### ISSUE TITLE
First screen after fresh installation and missing links

### ISSUE THREAD

**Issue by cavo789** [saleem-hadad/larecipe#8]
I've installed the package with `composer require binarytorch/larecipe` and forget to run `php artisan larecipe:install`.

The look&feel of `mysite/docs` give this:

![2018-09-08_11h58_57](https://user-images.githubusercontent.com/355999/45252927-a87f1a80-b35e-11e8-81f3-a6ad2a00ced1.png)

Oups, something is wrong (perhaps you can detect the absence of your template?) and show a nice message "Please don't forget to fire `php artisan larecipe:install`."

So, I run the artisan command and now the screen looks like better but there are a lot of errors in my console.

![2018-09-08_12h03_19](https://user-images.githubusercontent.com/355999/45252970-2e9b6100-b35f-11e8-9d9e-09227abd3902.png)

Indeed, no fonts and no logo at the top left.

I've tested under a totally new installation (`Laravel new larecipe`) which is, today, on Laravel 5.7.2.

**Comment by saleem-hadad** [comment]
Hi @cavo789 
Thank you very much for your contribution and finding the mentioned bugs and issues.

1. I really like your idea of showing a small feedback when a user forgets to run the install command and now this enhancement available on dev-master and will be added to the upcoming version. [See here](https://github.com/saleem-hadad/larecipe/commit/1a758d27dceb3cec2ce589ef3f0c8ecf9fce843e)

<img width="387" alt="screen shot 2018-09-09 at 2 07 18 am" src="https://user-images.githubusercontent.com/12780866/45257235-71981b80-b3d5-11e8-8f57-e8fbf1609c49.png">

2. Regarding your installation with Laravel v5.7, I'm not quite sure what's the problem of preventing the assets of showing up. I reproduced the installation with fresh laravel 5.7 installation and here is my output.

<img width="1280" alt="screen shot 2018-09-09 at 1 58 57 am" src="https://user-images.githubusercontent.com/12780866/45257255-ca67b400-b3d5-11e8-9842-30fbe4051491.png">
<img width="1280" alt="screen shot 2018-09-09 at 1 59 36 am" src="https://user-images.githubusercontent.com/12780866/45257256-cb98e100-b3d5-11e8-8c1b-b6486e347c07.png">
<img width="1280" alt="screen shot 2018-09-09 at 2 00 20 am" src="https://user-images.githubusercontent.com/12780866/45257257-ccca0e00-b3d5-11e8-9917-eaae5b3ee596.png">
<img width="1280" alt="screen shot 2018-09-09 at 2 00 25 am" src="https://user-images.githubusercontent.com/12780866/45257259-cdfb3b00-b3d5-11e8-96a3-bfe1452bf47b.png">
<img width="1280" alt="screen shot 2018-09-09 at 2 00 36 am" src="https://user-images.githubusercontent.com/12780866/45257262-d81d3980-b3d5-11e8-8921-947e9744d89c.png">
<img width="1280" alt="screen shot 2018-09-09 at 2 00 56 am" src="https://user-images.githubusercontent.com/12780866/45257263-d9e6fd00-b3d5-11e8-86ec-f23c03333b94.png">

However, if you can see in my console the only thing is missing is the app logo which is solved now by showing the default larecipe logo instead of confusing a user with blank image unless the user changes the app logo in the config, [see here](https://github.com/saleem-hadad/larecipe/commit/ebace697017ec9a4d863d465b9e9ca2b677d686b).

One gatcha I guess what prevents showing the assets in your case is the cache in your browser when hit the /docs for the first time before running the install command, could you please clear your cache and tell me back I'll be happy to help you out.

Thank you again 😍
