### ISSUE TITLE
Directory support

### ISSUE THREAD

**Issue by gpsietzema** [saleem-hadad/larecipe#96]
**Is your feature request related to a problem? Please describe.**
The documentation I'm making contains some serious folder structure, but Larecipe doesn't seem to support that currently.

**Describe the solution you'd like**
Have folder/directory support. E.g.
```
docs/1.0/topic-01/index.md
docs/1.0/topic-02/index.md
docs/1.0/topic-03/index.md
```

**Describe alternatives you've considered**
I've considered prefixing filesnames with fake foldernames, eg:
```
docs/1.0/topic-01_index.md
docs/1.0/topic-02_index.md
docs/1.0/topic-03_index.md
```

**Additional context**
Nothing really. I love Larecipe btw!

**Comment by saleem-hadad** [comment]
Hi @gpsietzema 
Thanks for your question 
It actually supports this functionality since 1.1 as I remember 
However, here's an example of docs that I have in one of my projects

<img width="294" alt="screenshot 2019-02-28 at 6 59 23 pm" src="https://user-images.githubusercontent.com/12780866/53561696-8a1a0f00-3b8a-11e9-808a-96b4db84e00a.png">

<img width="638" alt="screenshot 2019-02-28 at 6 59 33 pm" src="https://user-images.githubusercontent.com/12780866/53561705-8c7c6900-3b8a-11e9-91ce-0f9f6db4db9a.png">
